### ISSUE TITLE
Subtlety: The .stories elements overlap the images in the News section.

### ISSUE THREAD

**Issue by josephtkim** [pboone18/Colmar#5]
The .stories elements overlap the images when resizing the page. Consider adding a property like 

```css
.stories { 
  margin-left: 40px;
}
```

or whatever works to remove this overlapping.
